#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 04:00:00
#SBATCH -J taxonomic_script_001
#SBATCH -e error_taxonomic
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=taxonomic_output

# Load modules
module load bioinfo-tools
module load qiime2/2024.10

# Commands

#Denoising - change X to values based on the quality plots
qiime dada2 denoise-single \
  --i-demultiplexed-seqs demultiplexed-sequences.qza \
  --p-trunc-len 225 \
  --p-max-ee 2 \
  --p-chimera-method consensus \
  --o-representative-sequences asv-sequences-0.qza \
  --o-table feature-table-0.qza \
  --o-denoising-stats dada2-stats.qza

#Reviewing run statistics
qiime metadata tabulate \
  --m-input-file dada2-stats.qza \
  --o-visualization dada2-stats-summ.qzv

#Summaries of feature data and feature table
qiime feature-table summarize \
  --i-table feature-table-0.qza \
  --m-sample-metadata-file SraRunTable.tsv \
  --o-visualization feature-table-0-summ.qzv
qiime feature-table tabulate-seqs \
  --i-data asv-sequences-0.qza \
  --o-visualization asv-sequences-0-summ.qzv

#Filtering?

#Taxonomy assignment - change the link & double check the read link
wget \
  -O '16S-nb-classifier.qza' \
  'https://data.qiime2.org/classifiers/sklearn-1.4.2/greengenes2/2022.10.backbone.full-length.nb.sklearn-1.4.2.qza'

qiime feature-classifier classify-sklearn \
  --i-classifier 16S-nb-classifier.qza \
  --i-reads asv-sequences-0.qza  \
  --o-classification taxonomy.qza

qiime metadata tabulate \
  --m-input-file taxonomy.qza \
  --o-visualization taxonomy.qzv

#Taxonomic composition barplots - metadata?
qiime taxa barplot \
  --i-table feature-table-0.qza \
  --i-taxonomy taxonomy.qza \
  --m-metadata-file SraRunTable.tsv \
  --o-visualization taxa-bar-plots-1.qzv
