#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J importing_sequences_script_illumina_002
#SBATCH -e error_importing_illumina
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=importing_output_illumina

# Load modules
module load bioinfo-tools
module load qiime2

# Commands
qiime tools import \
  --type 'SampleData[PairedEndSequencesWithQuality]' \
  --input-format PairedEndFastqManifestPhred33 \
  --input-path 01_Input_data/manifest-file_illumina_single.csv \
  --output-path 02_Output_data/demultiplexed-sequences_illumina_single.qza

qiime demux summarize \
  --i-data 02_Output_data/demultiplexed-sequences_illumina_single.qza \
  --o-visualization 03_Results/demultiplexed-sequences-summ_illumina_single.qzv
