#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J importing_sequences_script_001
#SBATCH -e error_importing
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=importing_output

# Load modules
module load bioinfo-tools
module load qiime2

# Commands
qiime tools import \
  --type 'SampleData[SequencesWithQuality]' \
  --input-format SingleEndFastqManifestPhred33 \
  --input-path 01_Input_data/manifest-file.csv \
  --output-path 02_Output_data/demultiplexed-sequences.qza

qiime demux summarize \
  --i-data 02_Output_data/demultiplexed-sequences.qza \
  --o-visualization 02_Output_data/demultiplexed-sequences-summ.qzv
