#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 04:00:00
#SBATCH -J taxonomic_script_001
#SBATCH -e error_taxonomic
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=taxonomic_output

# Load modules
module load bioinfo-tools
module load qiime2/2024.10

# Commands

#Denoising - change to values based on the quality plots
qiime dada2 denoise-single \
  --i-demultiplexed-seqs 02_Output_data/demultiplexed-sequences.qza \
  --p-trunc-len 225 \
  --p-max-ee 2 \
  --p-chimera-method consensus \
  --o-representative-sequences 02_Output_data/asv-sequences-0.qza \
  --o-table 02_Output_data/feature-table-0.qza \
  --o-denoising-stats 02_Output_data/dada2-stats.qza

#Reviewing run statistics
qiime metadata tabulate \
  --m-input-file 02_Output_data/dada2-stats.qza \
  --o-visualization 03_Results/dada2-stats-summ.qzv

#Summaries of feature data and feature table
qiime feature-table summarize \
  --i-table 02_Output_data/feature-table-0.qza \
  --m-sample-metadata-file 02_Output_data/manifest-file.tsv \
  --o-visualization 03_Results/feature-table-0-summ.qzv
qiime feature-table tabulate-seqs \
  --i-data 02_Output_data/asv-sequences-0.qza \
  --o-visualization 03_Results/asv-sequences-0-summ.qzv

#Filtering?

#Taxonomy assignment - change the link & double check the read link
wget \
  -O '16S-nb-classifier.qza' \
  'https://data.qiime2.org/classifiers/sklearn-1.4.2/greengenes2/2022.10.backbone.full-length.nb.sklearn-1.4.2.qza'

qiime feature-classifier classify-sklearn \
  --i-classifier 16S-nb-classifier.qza \
  --i-reads 02_Output_data/asv-sequences-0.qza  \
  --o-classification 02_Output_data/taxonomy.qza

qiime metadata tabulate \
  --m-input-file 02_Output_data/taxonomy.qza \
  --o-visualization 03_Results/taxonomy.qzv

#Taxonomic composition barplots - metadata?
qiime taxa barplot \
  --i-table 02_Output_data/feature-table-0.qza \
  --i-taxonomy 02_Output_data/taxonomy.qza \
  --m-metadata-file 01_Input_data/manifest_file.tsv \
  --o-visualization 03_Results/taxa-bar-plots-1.qzv
