#!/bin/bash -l
#SBATCH -A uppmax2024-2-7
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 04:00:00
#SBATCH -J importing_sequences_script_fasta_pacbio_silva_001
#SBATCH -e error_taxonomic_fasta_pacbio
#SBATCH --mail-type=ALL
#SBATCH --mail-user emblap@hotmail.se
#SBATCH --output=taxonomic_output_fasta_pacbio

# Load modules
module load bioinfo-tools
module load qiime2/2024.10

# Commands
input_folder=/home/embla/Applied-bioinformatics/01_Extract_regions/02_Output_data/Individual_v1v9
output_folder=/home/embla/Applied-bioinformatics/04_Taxonomic_assignment/02_Output_data/fasta_pacbio_silva
result_folder=/home/embla/Applied-bioinformatics/04_Taxonomic_assignment/03_Results/fasta_pacbio_silva

for file in $(ls $input_folder)
do
qiime tools import \
  --type 'FeatureData[Sequence]' \
  --input-path $input_folder/$file \
  --output-path $output_folder/${file}.qza
done

#Taxonomy assignment - change the link & double check the read link
wget \
  -O '16S-nb-silva-classifier.qza' \
  'https://data.qiime2.org/classifiers/sklearn-1.4.2/silva/silva-138-99-nb-classifier.qza'

for file in $(ls $output_folder/*.1.fasta.qza)
do
name=$(basename -s .fasta.qza "$file")
qiime feature-classifier classify-sklearn \
  --i-classifier 16S-nb-silva-classifier.qza \
  --i-reads $output_folder/${name}.fasta.qza  \
  --o-classification $output_folder/taxonomy_${name}.qza

qiime metadata tabulate \
  --m-input-file $output_folder/taxonomy_${name}.qza \
  --o-visualization $result_folder/taxonomy_${name}.qzv
done
